"""tasks last_run_at field

Revision ID: 4567e665dff0
Revises: dc943cef08f8
Create Date: 2026-03-13 23:48:48.221096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4567e665dff0'
down_revision: Union[str, Sequence[str], None] = 'dc943cef08f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.create_index('idx_tasks_active_next_run', 'tasks', ['is_active', 'next_run_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasks_active_next_run', table_name='tasks')
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.drop_column('tasks', 'next_run_at')
    # ### end Alembic commands ###
