"""task new field

Revision ID: 7baaffb93d71
Revises: 913ebf36345a
Create Date: 2026-03-04 22:08:20.721976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7baaffb93d71'
down_revision: Union[str, Sequence[str], None] = '913ebf36345a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('last_run_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'last_run_at')
    # ### end Alembic commands ###
